# Configuration file for quality-control.

[general]
    input_file ='/home/rrealrangel/MEGA/datasets/imta_bandas/data/rh01/01002.mdb'

    [level_1_tests]
        # Tests performed on raw data.
        gross_range_test = false
        climatology_test = true
        spikes_data_test = false
        change_rate_test = true
        flat_series_test = true

    [level_2_tests]
        # Tests performed in digested data.
        missd_ratio_test = true