# Configuration file for quality-control.

[general]
    input_dir='/home/rrealrangel/MEGA/proyectos/2019/2019-inv-01_cathments-classification/main/analisys/sg30057/precipitation/climatological_stations'
    output_dir='/home/rrealrangel/MEGA/proyectos/2019/2019-inv-01_cathments-classification/main/analisys/sg30057/precipitation/qc_outputs'

[level_1_tests]
    # Tests performed on raw data.
    gross_range_test = false
    climatology_test = true
    spikes_data_test = false
    change_rate_test = true
    flat_series_test = true
    tmp_outlier_test = false