# Configuration file for quality-control.

[general]
    input_dir='C:/Users/rreal/OneDrive/datasets/imta_bandas/data/corrientes'
    output_dir='C:/Users/rreal/OneDrive/proyectos/2019/2019-inv-01_cathments-classification/main/analisys/time_series_quality_control/daily_streamflow'

[level_1_tests]
    # Tests performed on raw data.
    gross_range_test = false
    climatology_test = true
    spikes_data_test = false
    change_rate_test = true
    flat_series_test = true
    tmp_outlier_test = false